name: Automatic Lowering Dapp Release

on:
  push:
    branches:
      - main

jobs:
  github-release:
    uses: AventusDAO/shared-workflows/.github/workflows/automatic-releases.yaml@v5.20.0
    with:
      default_bump: minor
    secrets:
      envPat: ${{ secrets.VERENFT_CI_AGENT_TOKEN }}
