name: Docker Build

on:
  workflow_call:
    inputs:
      runner:
        required: false
        type: string
        default: gh-ubuntu-2404-x64
      config_creds:
        required: false
        type: boolean
        default: true
      aws_region:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      short_image_name:
        required: true
        type: string
      ecr_repository_prefix:
        required: true
        type: string
    secrets:
      aws_access_key:
        required: false
      aws_secret_key:
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  docker-build:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        if: ${{ inputs.config_creds }}
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key }}
          aws-secret-access-key: ${{ secrets.aws_secret_key }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to the AWS registry
        run: |
          aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com

      - name: Create tag for PR
        if: github.ref != 'refs/heads/master'
        run: echo "DOCKER_TAG=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create tag for merge
        if: github.ref == 'refs/heads/master'
        run: echo "DOCKER_TAG=${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:${GITHUB_SHA::7},${{ inputs.aws_account_id }}.dkr.ecr.${{ inputs.aws_region }}.amazonaws.com/${{ inputs.ecr_repository_prefix }}/${{ inputs.short_image_name }}:latest" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.DOCKER_TAG }}
